DROP TABLE IF EXISTS users, films, mpa, genre, film_genre, film_likes, friends_user CASCADE;

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    email VARCHAR(60) NOT NULL,
    login VARCHAR(60) NOT NULL,
    birthday DATE NOT NULL
    );

CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    description VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL
    );

CREATE TABLE IF NOT EXISTS MPA (
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name VARCHAR(20) NOT NULL
    );

CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(60) NOT NULL
    );

CREATE TABLE IF NOT EXISTS likes (
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS friends (
    friend_one_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    friend_two_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    status boolean
    );

CREATE TABLE IF NOT EXISTS film_genre (
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genre (genre_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS film_MPA (
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    mpa_id INTEGER REFERENCES MPA (mpa_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, mpa_id)
    );


